BEGIN;

CREATE SCHEMA IF NOT EXISTS whatsapp;
SET LOCAL search_path TO whatsapp, public;

CREATE TABLE IF NOT EXISTS tenants (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  legal_name TEXT,
  ruc TEXT,
  address TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused')),
  timezone TEXT NOT NULL DEFAULT 'America/Bogota',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS whatsapp_numbers (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  phone_number_id TEXT NOT NULL UNIQUE,
  waba_id TEXT,
  display_name TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_catalog (
  role_key TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 100,
  assignable BOOLEAN NOT NULL DEFAULT TRUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO role_catalog (role_key, label, description, sort_order)
VALUES
  ('cat', 'Gato Manolo', 'Asistente general con personalidad gatuna.', 10),
  ('quotes', 'Cotizaciones', 'Crea y administra cotizaciones en PDF.', 20),
  ('print-advisor', 'Asesor de impresión', 'Consulta ventas y operación del negocio de impresión.', 30),
  ('store-designer', 'Diseñador de tienda', 'Genera y administra propuestas de productos.', 40),
  ('enterprise-advisor', 'Asesor empresarial', 'Comprobantes electrónicos multiempresa.', 50)
ON CONFLICT (role_key) DO UPDATE SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  active = TRUE,
  updated_at = CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS bot_configs (
  tenant_id TEXT PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  system_prompt TEXT NOT NULL,
  ai_provider TEXT NOT NULL DEFAULT 'groq',
  ai_model TEXT,
  temperature DOUBLE PRECISION NOT NULL DEFAULT 0.8,
  max_tokens INTEGER NOT NULL DEFAULT 180,
  role_key TEXT NOT NULL DEFAULT 'cat',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  whatsapp_user_id TEXT NOT NULL,
  display_phone TEXT,
  phone_e164 TEXT CHECK (
    phone_e164 IS NULL OR phone_e164 ~ '^\+[1-9][0-9]{7,14}$'
  ),
  display_name TEXT,
  active_role_key TEXT,
  last_seen_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, whatsapp_user_id)
);

CREATE TABLE IF NOT EXISTS contact_role_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  previous_role_key TEXT,
  new_role_key TEXT,
  changed_by TEXT NOT NULL DEFAULT 'users-tui',
  changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversations (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'closed', 'handed_off')),
  last_message_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  conversation_id TEXT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  meta_message_id TEXT,
  direction TEXT NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  message_type TEXT NOT NULL DEFAULT 'text',
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'received',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, meta_message_id)
);

CREATE TABLE IF NOT EXISTS quote_configs (
  tenant_id TEXT PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
  legal_name TEXT NOT NULL,
  tax_id TEXT NOT NULL,
  address TEXT NOT NULL,
  services_json TEXT NOT NULL DEFAULT '[]',
  bank_name TEXT NOT NULL DEFAULT '',
  bank_account TEXT NOT NULL DEFAULT '',
  bank_cci TEXT NOT NULL DEFAULT '',
  advisor_name TEXT NOT NULL DEFAULT '',
  advisor_phone TEXT NOT NULL DEFAULT '',
  currency TEXT NOT NULL DEFAULT 'PEN',
  tax_rate NUMERIC(8, 6) NOT NULL DEFAULT 0.18,
  prices_include_tax BOOLEAN NOT NULL DEFAULT TRUE,
  valid_days INTEGER NOT NULL DEFAULT 7,
  logo_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote_sequence_scopes (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  next_number INTEGER NOT NULL DEFAULT 100 CHECK (next_number > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote_drafts (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  sequence_scope_id TEXT REFERENCES quote_sequence_scopes(id),
  status TEXT NOT NULL DEFAULT 'collecting'
    CHECK (status IN ('collecting', 'ready', 'confirmed', 'sent', 'cancelled')),
  quote_number TEXT,
  customer_name TEXT NOT NULL DEFAULT '',
  customer_tax_id TEXT NOT NULL DEFAULT '',
  customer_phone TEXT NOT NULL DEFAULT '',
  issued_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  importe_letras TEXT NOT NULL DEFAULT '',
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quote_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  draft_id TEXT NOT NULL REFERENCES quote_drafts(id) ON DELETE CASCADE,
  position INTEGER NOT NULL,
  description TEXT NOT NULL,
  quantity NUMERIC(18, 4) NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(18, 4) NOT NULL CHECK (unit_price >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (draft_id, position)
);

CREATE TABLE IF NOT EXISTS quote_sequence_members (
  scope_id TEXT NOT NULL REFERENCES quote_sequence_scopes(id) ON DELETE CASCADE,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, contact_id),
  UNIQUE (scope_id, contact_id)
);

CREATE TABLE IF NOT EXISTS contact_role_states (
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  role_key TEXT NOT NULL,
  state_json TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, contact_id, role_key)
);

CREATE TABLE IF NOT EXISTS conversation_sessions (
  id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  role_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'expired', 'closed')),
  state_json TEXT NOT NULL DEFAULT '{}',
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  scope TEXT NOT NULL,
  key TEXT NOT NULL,
  request_hash CHAR(64) NOT NULL,
  status TEXT NOT NULL DEFAULT 'processing'
    CHECK (status IN ('processing', 'completed', 'failed')),
  response_json TEXT,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, scope, key)
);

CREATE TABLE IF NOT EXISTS store_payment_notifications (
  tenant_id TEXT NOT NULL,
  order_id TEXT NOT NULL,
  payment_id TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, order_id, payment_id)
);

CREATE TABLE IF NOT EXISTS bridge_requests (
  request_id TEXT PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  role_key TEXT NOT NULL,
  request_hash CHAR(64) NOT NULL,
  status TEXT NOT NULL DEFAULT 'processing'
    CHECK (status IN ('processing', 'completed', 'failed')),
  response_text TEXT,
  error_code TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tenant_members (
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  display_name TEXT,
  permissions JSONB NOT NULL DEFAULT
    '["view_invoice","create_invoice","issue_invoice","create_credit_note"]'::jsonb,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, contact_id),
  CHECK (jsonb_typeof(permissions) = 'array')
);

CREATE TABLE IF NOT EXISTS tenant_integrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  provider TEXT NOT NULL DEFAULT 'facturaya' CHECK (provider = 'facturaya'),
  encrypted_token TEXT NOT NULL,
  environment TEXT NOT NULL DEFAULT 'production'
    CHECK (environment IN ('beta', 'production')),
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive')),
  last_connection_check TIMESTAMPTZ,
  last_connection_status TEXT
    CHECK (last_connection_status IS NULL OR last_connection_status IN ('ok', 'failed')),
  last_connection_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, provider)
);

CREATE TABLE IF NOT EXISTS facturaya_sessions (
  channel_tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  active_tenant_id TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (channel_tenant_id, contact_id),
  FOREIGN KEY (active_tenant_id, contact_id)
    REFERENCES tenant_members(tenant_id, contact_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS facturaya_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  contact_id BIGINT NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT,
  operation TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  idempotency_key TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('started', 'completed', 'failed')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_whatsapp_numbers_tenant_id
  ON whatsapp_numbers (tenant_id);
CREATE INDEX IF NOT EXISTS idx_bot_configs_role_key
  ON bot_configs (role_key);
CREATE INDEX IF NOT EXISTS idx_contacts_tenant_id
  ON contacts (tenant_id);
CREATE INDEX IF NOT EXISTS idx_contacts_active_role
  ON contacts (tenant_id, active_role_key);
CREATE INDEX IF NOT EXISTS idx_contacts_tenant_last_seen
  ON contacts (tenant_id, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_role_catalog_assignable
  ON role_catalog (active, assignable, sort_order);
CREATE INDEX IF NOT EXISTS idx_contact_role_audit_contact
  ON contact_role_audit (tenant_id, contact_id, changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_tenant_status
  ON conversations (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_created
  ON messages (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_messages_tenant_created
  ON messages (tenant_id, created_at);
CREATE INDEX IF NOT EXISTS idx_quote_drafts_contact_status
  ON quote_drafts (tenant_id, contact_id, status, updated_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_quote_drafts_one_active
  ON quote_drafts (tenant_id, contact_id)
  WHERE status IN ('collecting', 'ready', 'confirmed');
CREATE INDEX IF NOT EXISTS idx_quote_items_draft
  ON quote_items (draft_id, position);
CREATE INDEX IF NOT EXISTS idx_quote_sequence_scopes_tenant
  ON quote_sequence_scopes (tenant_id, name);
CREATE INDEX IF NOT EXISTS idx_quote_sequence_members_scope
  ON quote_sequence_members (scope_id);
CREATE INDEX IF NOT EXISTS idx_contact_role_states_contact
  ON contact_role_states (tenant_id, contact_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversation_sessions_active_contact
  ON conversation_sessions (tenant_id, contact_id)
  WHERE status = 'open';
CREATE INDEX IF NOT EXISTS idx_conversation_sessions_expiration
  ON conversation_sessions (status, expires_at);
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_expiration
  ON idempotency_keys (expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS store_payment_notifications_order_idx
  ON store_payment_notifications (tenant_id, order_id);
CREATE INDEX IF NOT EXISTS idx_bridge_requests_tenant_created
  ON bridge_requests (tenant_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tenants_ruc_unique
  ON tenants (ruc)
  WHERE ruc IS NOT NULL AND BTRIM(ruc) <> '';
CREATE INDEX IF NOT EXISTS idx_contacts_phone_e164
  ON contacts (phone_e164)
  WHERE phone_e164 IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tenant_members_contact
  ON tenant_members (contact_id, status);
CREATE INDEX IF NOT EXISTS idx_tenant_integrations_status
  ON tenant_integrations (provider, status);
CREATE INDEX IF NOT EXISTS idx_facturaya_sessions_expiration
  ON facturaya_sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_facturaya_audit_tenant_created
  ON facturaya_audit_logs (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_facturaya_audit_contact_created
  ON facturaya_audit_logs (contact_id, created_at DESC);

COMMIT;
