BEGIN;

CREATE TABLE IF NOT EXISTS whatsapp.role_catalog (
  role_key TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 100,
  assignable BOOLEAN NOT NULL DEFAULT TRUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO whatsapp.role_catalog (
  role_key,
  label,
  description,
  sort_order
)
VALUES
  ('cat', 'Gato Manolo', 'Asistente general con personalidad gatuna.', 10),
  ('finance', 'Finanzas', 'Registro básico de ingresos y egresos.', 20),
  ('quotes', 'Cotizaciones', 'Crea y administra cotizaciones en PDF.', 30),
  ('finance-cat', 'Gato financiero', 'Asistente gatuno con orientación financiera.', 40),
  ('print-advisor', 'Asesor de impresión', 'Consulta ventas y operación del negocio de impresión.', 50),
  ('store-designer', 'Diseñador de tienda', 'Genera y administra propuestas de productos.', 60),
  ('finance-player-cat', 'Gato Finanzas Player', 'Registra movimientos en Finanzas Player.', 70),
  ('enterprise-advisor', 'Asesor empresarial', 'Finanzas y comprobantes electrónicos para empresa.', 80)
ON CONFLICT (role_key) DO UPDATE SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  sort_order = EXCLUDED.sort_order,
  active = TRUE,
  updated_at = CURRENT_TIMESTAMP;

ALTER TABLE whatsapp.contacts
  ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;

UPDATE whatsapp.contacts AS contact
SET last_seen_at = activity.last_seen_at
FROM (
  SELECT
    conversation.contact_id,
    MAX(COALESCE(message.created_at, conversation.last_message_at)) AS last_seen_at
  FROM whatsapp.conversations AS conversation
  LEFT JOIN whatsapp.messages AS message
    ON message.conversation_id = conversation.id
  GROUP BY conversation.contact_id
) AS activity
WHERE activity.contact_id = contact.id
  AND contact.last_seen_at IS NULL;

CREATE TABLE IF NOT EXISTS whatsapp.contact_role_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES whatsapp.tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES whatsapp.contacts(id) ON DELETE CASCADE,
  previous_role_key TEXT,
  new_role_key TEXT,
  changed_by TEXT NOT NULL DEFAULT 'users-tui',
  changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_contacts_tenant_last_seen
  ON whatsapp.contacts (tenant_id, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_role_catalog_assignable
  ON whatsapp.role_catalog (active, assignable, sort_order);

CREATE INDEX IF NOT EXISTS idx_contact_role_audit_contact
  ON whatsapp.contact_role_audit (tenant_id, contact_id, changed_at DESC);

COMMIT;
