BEGIN;

ALTER TABLE whatsapp.tenants
  ADD COLUMN IF NOT EXISTS legal_name TEXT,
  ADD COLUMN IF NOT EXISTS ruc TEXT,
  ADD COLUMN IF NOT EXISTS address TEXT;

ALTER TABLE whatsapp.contacts
  ADD COLUMN IF NOT EXISTS phone_e164 TEXT;

UPDATE whatsapp.contacts
SET phone_e164 = '+' || whatsapp_user_id
WHERE phone_e164 IS NULL
  AND whatsapp_user_id ~ '^[1-9][0-9]{7,14}$';

DO $$
BEGIN
  ALTER TABLE whatsapp.contacts
    ADD CONSTRAINT whatsapp_contacts_phone_e164_format
    CHECK (phone_e164 IS NULL OR phone_e164 ~ '^\+[1-9][0-9]{7,14}$');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS whatsapp_tenants_ruc_unique
  ON whatsapp.tenants (ruc)
  WHERE ruc IS NOT NULL AND BTRIM(ruc) <> '';

CREATE INDEX IF NOT EXISTS whatsapp_contacts_phone_e164
  ON whatsapp.contacts (phone_e164)
  WHERE phone_e164 IS NOT NULL;

CREATE TABLE IF NOT EXISTS whatsapp.tenant_members (
  tenant_id TEXT NOT NULL REFERENCES whatsapp.tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES whatsapp.contacts(id) ON DELETE CASCADE,
  display_name TEXT,
  permissions JSONB NOT NULL DEFAULT
    '["view_invoice","create_invoice","issue_invoice","create_credit_note"]'::jsonb,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (tenant_id, contact_id),
  CHECK (jsonb_typeof(permissions) = 'array')
);

CREATE TABLE IF NOT EXISTS whatsapp.tenant_integrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES whatsapp.tenants(id) ON DELETE CASCADE,
  provider TEXT NOT NULL DEFAULT 'facturaya'
    CHECK (provider = 'facturaya'),
  encrypted_token TEXT NOT NULL,
  environment TEXT NOT NULL DEFAULT 'production'
    CHECK (environment IN ('beta', 'production')),
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive')),
  last_connection_check TIMESTAMPTZ,
  last_connection_status TEXT
    CHECK (last_connection_status IS NULL OR last_connection_status IN ('ok', 'failed')),
  last_connection_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (tenant_id, provider)
);

CREATE TABLE IF NOT EXISTS whatsapp.facturaya_sessions (
  channel_tenant_id TEXT NOT NULL REFERENCES whatsapp.tenants(id) ON DELETE CASCADE,
  contact_id BIGINT NOT NULL REFERENCES whatsapp.contacts(id) ON DELETE CASCADE,
  active_tenant_id TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (channel_tenant_id, contact_id),
  FOREIGN KEY (active_tenant_id, contact_id)
    REFERENCES whatsapp.tenant_members(tenant_id, contact_id)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS whatsapp.facturaya_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id TEXT NOT NULL REFERENCES whatsapp.tenants(id) ON DELETE RESTRICT,
  contact_id BIGINT NOT NULL REFERENCES whatsapp.contacts(id) ON DELETE RESTRICT,
  operation TEXT NOT NULL,
  resource_type TEXT,
  resource_id TEXT,
  idempotency_key TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('started', 'completed', 'failed')),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS whatsapp_tenant_members_contact
  ON whatsapp.tenant_members (contact_id, status);
CREATE INDEX IF NOT EXISTS whatsapp_tenant_integrations_status
  ON whatsapp.tenant_integrations (provider, status);
CREATE INDEX IF NOT EXISTS whatsapp_facturaya_sessions_expiration
  ON whatsapp.facturaya_sessions (expires_at);
CREATE INDEX IF NOT EXISTS whatsapp_facturaya_audit_tenant_created
  ON whatsapp.facturaya_audit_logs (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS whatsapp_facturaya_audit_contact_created
  ON whatsapp.facturaya_audit_logs (contact_id, created_at DESC);

COMMIT;
